### ISSUE TITLE
TF-Lite human detection model

### ISSUE THREAD

**Issue by quockhanh1198** [intel-isl/OpenBot#123]
Hi Thias, can you tell me about the mobilenet-ssd model you use in this project about things like: input size and type, output size and type,....please ? And another one is the difference between 2 models v1.1.0 and v3.small you used,  thank you so much bro !

**Comment by thias15** [comment]
The main difference is that the model with MobileNetV3 backbone runs faster on most phones and processes the images at 320x320 instead of 300x300. For more details, please read the papers and the config in the code. 

MobileNetV1: [Paper](https://arxiv.org/abs/1704.04861), [Code](https://github.com/intel-isl/OpenBot/blob/master/android/app/src/main/java/org/openbot/tflite/DetectorQuantizedMobileNetV1.java)
MobileNetV3: [Paper](https://arxiv.org/abs/1905.02244), [Code](https://github.com/intel-isl/OpenBot/blob/master/android/app/src/main/java/org/openbot/tflite/DetectorQuantizedMobileNetV3.java)
