### ISSUE TITLE
Separate designator for second U1 pin header

### ISSUE THREAD

**Issue by agios** [intel-isl/OpenBot#61]
Could the second pin header get a separate designator in the BOM, also adding it to the centroid file?

As it is, when requesting assembly for the custom PCB, PCBWay complains that they do not know where to place it

**Comment by thias15** [comment]
Unfortunately it's no so easy to do this, since the footprint is associated with the silk screen and a 3D model of pin headers and Arduino. Just adding a new designator on the PCB and updating the BOM would be easy though. I guess the centroid file could be adjusted manually? But usually through-hole components are mounted manually anyways.
