### ISSUE TITLE
Sonarr and indicator not working

### ISSUE THREAD

**Issue by yangtfu** [intel-isl/OpenBot#62]
I'm not familear with JAVA, so I just test the arduino firmware, sonar and indicator LED seem work fine. But when I pugin the phone and make it follow a person, the robot bump around and the indictors never light up. Is there anything wrong with my android app?

**Comment by thias15** [comment]
Your Android app is fine. For the person following neither the indicator nor the ultrasonic sensor are used. That being said, I will probably implement stopping based on the ultrasonic sensor, since several people have expressed interest in this feature. The indicators are only used for training autonomous driving policies.
